Matrix Multiplication

soal 1

using Numpy

In [1]:
import numpy as np

In [2]:
#buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
b = np.array([[1],
              [2],
              [3]])
b

array([[1],
       [2],
       [3]])

using pytorch

In [4]:
import torch

In [5]:
#buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
A_pt

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
b_pt = torch.tensor([[1],
                      [2],
                      [3]])
b_pt

tensor([[1],
        [2],
        [3]])

using tensorflow

In [9]:
import tensorflow as tf

In [10]:
#buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
A_tf = tf.Variable([[1, 2, 3], [4, 5, 6]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [11]:
b_tf = tf.Variable([[1],
                    [2],
                    [3]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

soal 2

In [12]:
#tampilkan ukuran matrix A dan vector b
A.shape, b.shape

((2, 3), (3, 1))

soal 3

In [13]:
#kalikan matrix A dengan vector b
np.dot(A, b) # even though technically dot products are between vectors only

array([[14],
       [32]])

In [14]:
#kalikan matrix A_pt dengan vector b_pt
hasil_pt = torch.matmul(A_pt, b_pt)
hasil_pt

tensor([[14],
        [32]])

In [15]:
#kalikan matrix A_tf dengan vector b_tf
hasil_tf = tf.matmul(A_tf, b_tf)
hasil_tf

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [32]], dtype=int32)>

soal 4

In [16]:
#buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8., 9]])
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
#buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
#buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

soal 5

In [19]:
#kalikan matrix A dengan matrix B
np.dot(A, B)

array([[30., 36., 42.],
       [66., 81., 96.]])

In [20]:
#kalikan matrix A_pt dengan matrix B_pt
torch.matmul(A_pt, B_pt)

tensor([[30, 36, 42],
        [66, 81, 96]])

In [21]:
#kalikan matrix A_tf dengan matrix B_tf
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

soal 6

In [22]:
# np.dot(B, A)

In [23]:
#buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
torch.matmul(A_pt, B_pt) # no need to change functions, unlike in TF

tensor([[30, 36, 42],
        [66, 81, 96]])

In [24]:
#buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
torch.matmul(B_pt, A_pt) # no need to change functions, unlike in TF


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x3)

kodingan error maka tidak komutatif. karena matriks tidak dapat dikalikan dan otomatis AB ≠ BA