In [4]:
# buat vector x dan y dengan ukuran 1x3 menggunakan numpy
import numpy as np

x = np.array([1, 2, 5])
x

array([1, 2, 5])

In [5]:
y = np.array([0, 1, 2])
y

array([0, 1, 2])

In [9]:
# buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch
import torch

x_pt = torch.tensor([3, 2, 6])
x_pt

tensor([3, 2, 6])

In [10]:
y_pt = torch.tensor([0, 4, 9])
y_pt

tensor([0, 4, 9])

In [11]:
# buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow
import tensorflow as tf

x_tf = tf.Variable([5, 2, 1])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 2, 1], dtype=int32)>

In [12]:
y_tf = tf.Variable([0, 1, 2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [13]:
# hitung perkalian dot product antara vector x dan vector y
np.dot(x, y)

np.int64(12)

In [14]:
# hitung perkalian dot product antara vector x_pt dan vector y_pt
torch.dot(x_pt, y_pt)

tensor(62)

In [15]:
# hitung perkalian dot product antara vector x_tf dan vector y_tf
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [16]:
# lakukan perhitungan excercise menggunakan collab
y = np.array([[42,4,7,99],
              [-99,-3,17,22]
])
y_t = y.T
y_t

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [17]:
a = np.array([[25,10],
              [-2,1]
])
b = np.array([[-1,7],
              [10,8]
])
(a*b)

array([[-25,  70],
       [-20,   8]])

In [18]:
w = np.array([-1,2,-2])
x = np.array([5,10,0])

np.dot(w, x)

np.int64(15)